image:
  file: .gitpod.Dockerfile
tasks:
  - name: start tasks
    env:
      TEXT: "start gitpod tasks!"
    command: |
      if [ -n "${TEXT}"]; then
        echo "TEXT"
      else
        echo "welcome to gitpod"
      fi  
  - name: show env
    init: gp env > gitpod.env
    command: | 
      echo "$VAR1"
      echo "$VAR2"
  - name: run task in order
    before: |
      echo 'ready to run scripts'
      echo 'before init'
    init: |
      echo 'install npm'
      gp env MSG=world
      echo "hello, ${MSG}"
    command: |
      echo 'start running scripts'
  - name: mysql-data-load
    before: gp ports await 3306
    init: |
      mysql < example-database.sql
    command: |
      gp sync-done mysql-data-load
      mysql -e 'SHOW TABLES FROM exampledatabase'
  - name: mysql-notification
    init: echo 'wait mysql ...'
    command: |
      gp sync-await mysql-data-load
      echo 'mysql load completed'
       
ports:
  - port: 3000
    onOpen: open-preview
    
github:
    prebuilds:
        # enable for the master/default branch (defaults to true)
        master: true
        # enable for all branches in this repo (defaults to false)
        branches: true
        # enable for pull requests coming from this repo (defaults to true)
        pullRequests: false
        # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
        addComment: false
