image:
  file: .gitpod.Dockerfile
tasks:
  - name: T1 - run task in order
    before: |
      echo 'ready to run scripts'
      echo 'before init'
    init: |
      echo 'install npm'
      npm install
    command: |
      echo 'start running dev'
      npm run dev
       
ports:
  - port: 3000
    onOpen: open-preview
