image: python:alpine3.7
tasks:
  - init: |
      apk add --no-cache bash
      apk add --update git curl vim tar tree
      apk add --no-cache openssl-dev build-base python3-dev libffi-dev openssh
      curl -L -s  -o /usr/bin/ttyd https://github.com/tsl0922/ttyd/releases/download/1.5.0/ttyd_linux.x86_64 
      chmod 755 /usr/bin/ttyd
